---
# handlers file for roles/apache

# les handlers sont des actions qui sont executés grâce à des triggers. Il se déclare comme des tasks et on l'appel dans les tasks avec "notify"
- name: enable apache2
  shell:
    cmd: systemctl enable apache2

- name: restart apache2
  shell:
    cmd: systemctl start apache2
