---
# tasks file for roles/apache

# ici je définis les tâches qui seront exécutées par le role apache
- name: Installation du packet Apache
  apt: # le module apt permet d'installer des paquets
    name: apache2
    state: latest
    update_cache: yes # permet de mettre à jour le cache des paquets
  notify: # permet d'appeler des handlers, ici j'appelle le handlers "restart apache2"
    - restart apache2

- name: Install PHP packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ php_packages }}"
  notify:
    - enable apache2
    - restart apache2