# cette t창che permet d'executer le role apache sur les serveurs du groupe apache
- name: Install apache
  hosts: apache
  become: yes
  roles:
    - role: apache

# cette t창che permet d'executer le role mariadb sur les serveurs du groupe mariadb
- name: install mariadb
  hosts: mariadb
  become: yes
  gather_facts: no
  roles:
    - role: mariadb

# cette t창che permet d'executer le role confdb sur les serveurs du groupe mariadb
- name: mediawiki db configuration
  hosts: mariadb
  gather_facts: no
  roles:
    - role: confdb

# cette t창che permet d'executer le role confapache sur les serveurs du groupe apache
- name: mediawiki apache configuration
  hosts: apache
  gather_facts: no
  roles:
    - role: confapache