- name: Install apache
  hosts: apache
  become: yes
  roles:
    - role: apache

- name: install mariadb
  hosts: mariadb
  become: yes
  gather_facts: no
  roles:
    - role: mariadb

- name: mediawiki db configuration
  hosts: mariadb
  gather_facts: no
  roles:
    - role: confdb

- name: mediawiki apache configuration
  hosts: apache
  gather_facts: no
  roles:
    - role: confapache