- name: Mon Playbook
  hosts: all
  tasks:
  - name: Afficher le hostname
    debug:
      msg: "Le hostname est {{ inventory_hostname }}"

- name: Create a directory
  hosts: all
  become: yes
  tasks:
  - name: Create a directory
    file:
      path: "/home/{{ myuser }}/myDir"
      state: directory
      mode: 0755
      owner: "{{ myuser }}"
  