- name: Mon Playbook # le nom de la tâche
  hosts: all # j'execute ce playbook sur tous les serveurs
  tasks:
  - name: Afficher le hostname
    debug: # le module debug permet d'afficher des messages
      msg: "Le hostname est {{ inventory_hostname }}" # ici j'affiche le hostname de la machine distante

- name: Create a directory
  hosts: all
  become: yes # permet de passer en mode privilégié
  tasks:
  - name: Create a directory
    file: # le module file permet de créer des fichiers ou des répertoires
      path: "/home/{{ ansible_user }}/myDir"
      state: directory # je crée un répertoire
      mode: 0755
      owner: "{{ ansible_user }}"
  