---
# handlers file for roles/mariadb
- name: start mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
    enabled: yes