---
# tasks file for roles/confapache
- name: add g+w sur le repertoire mediawiki
  command: "chmod -R g+w {{ mediawiki_directory }}"

- name: mediawiki config file
  become: yes
  args:
    chdir: "{{ mediawiki_maintenance_directory }}"
    creates: "{{ mediawiki_directory }}/LocalSettings.php"
  command:
    php install.php
      --dbname "{{ mediawiki_db_name }}"
      --dbserver "{{ mediawiki_db_host }}"
      --dbuser "{{ mediawiki_db_user }}"
      --dbpass "{{ mediawiki_db_password }}"
      --installdbuser "{{ mediawiki_db_user }}"
      --installdbpass "{{ mediawiki_db_password }}"
      --server "http://mediawiki:{{ port }}"
      --scriptpath "/{{ mediawiki_name }}"
      --lang "fr"
      --pass "{{ mediawiki_db_password }}"
      "{{ mediawiki_title }}"
      "{{ mediawiki_admin_user }}"
  run_once: yes
  #--server "http://{{ ansible_fqdn }}:{{ port }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups.apache }}"

- name: mediawiki db update
  become: yes
  command:
    php update.php --quick
  args:
    chdir: "{{ mediawiki_maintenance_directory }}"
  run_once: yes
  register: resultat
  changed_when: "' ...done.' in resultat.stdout"