---
# tasks file for roles/confapache

# ici je définis les tâches qui seront exécutées par le role confapache
- name: mediawiki directory
  file: # le module file permet de créer un répertoire ou un fichier, dans ce cas c'est un repertoire.
    path: "{{ mediawiki_directory }}"
    state: directory
    owner: "www-data"
    group: "www-data"

- name: mediawiki archive download
  unarchive: # le module unarchive permet de décompresser une fichier compressé
    src: "{{ mediawiki_archive_url }}"
    dest: "{{ apache_dir }}"
    remote_src: yes
    owner: "www-data"
    group: "www-data"

- name: mediawiki modify directory
  shell:  # le module shell permet d'exécuter des commandes shell
    cmd: "{{ item }}"
  with_items:
    - "cp -r {{ apache_dir }}/mediawiki-1.37.1/* {{ mediawiki_directory }}"

- name: pause for 30 seconds
  pause: # le module pause permet de mettre en pause l'exécution du playbook
    seconds: 30

- name: mediawiki rigths to www-data
  file: # le module file permet de créer un répertoire ou un fichier, dans ce cas, le repertoire existant, je change les droits.
    path: "{{ mediawiki_directory }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    recurse: yes

- name: add g+w sur le repertoire mediawiki
  command: "chmod -R g+w {{ mediawiki_directory }}"

- name: mediawiki config file
  become: yes
  args: # le module args permet de passer des arguments à une commande
    chdir: "{{ mediawiki_maintenance_directory }}"
    creates: "{{ mediawiki_directory }}/LocalSettings.php"
  command:
    php install.php
      --dbname "{{ mediawiki_db_name }}"
      --dbserver "{{ mediawiki_db_host }}"
      --dbuser "{{ mediawiki_db_user }}"
      --dbpass "{{ mediawiki_db_password }}"
      --installdbuser "{{ mediawiki_db_user }}"
      --installdbpass "{{ mediawiki_db_password }}"
      --server "http://mediawiki:{{ port }}"
      --scriptpath "/{{ mediawiki_name }}"
      --lang "fr"
      --pass "{{ mediawiki_db_password }}"
      "{{ mediawiki_title }}"
      "{{ mediawiki_admin_user }}"
  run_once: yes # permet de n'exécuter la tâche qu'une seule fois
  delegate_to: "{{ item }}" # permet d'exécuter la tâche sur un hôte spécifique
  with_items: "{{ groups.apache }}" # je fais une boucle sur le groupe de serveur 'apache'

- name: mediawiki db update
  become: yes
  command:
    php update.php --quick
  args:
    chdir: "{{ mediawiki_maintenance_directory }}"
  run_once: yes
  register: resultat
  changed_when: "' ...done.' in resultat.stdout"