---
# tasks file for roles/confdb
- name: mediawiki database creation
  mysql_db:
    name: "{{ mediawiki_db_name }}"
    state: present

- name: mediawiki user creation and privileges
  mysql_user:
    name: "{{ mediawiki_db_user }}"
    password: "{{ mediawiki_db_password }}"
    #priv: "{{ mediawiki_db_name }}.*:ALL"
    priv: "*.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
  - "{{ ansible_host_list }}"

- name: Create user for hosts
  shell:
    cmd: "mysql -u root  -e \"CREATE USER '{{ mediawiki_db_user }}'@'{{ item }}' IDENTIFIED BY '{{ mediawiki_db_password }}'\""
  with_items: "{{ ansible_host_list }}"

- name: Give access
  shell:
    cmd: "mysql -u root  -e \"Grant All Privileges ON *.* to '{{ mediawiki_db_user }}'@'{{ item }}' Identified By '{{ mediawiki_db_password }}'\""
  with_items: "{{ ansible_host_list }}"