---
# tasks file for roles/confdb

# ici je définis les tâches qui seront exécutées par le role confdb
- name: mediawiki database creation
  mysql_db:
    name: "{{ mediawiki_db_name }}"
    state: present

- name: mediawiki user creation and privileges
  mysql_user:
    name: "{{ mediawiki_db_user }}"
    password: "{{ mediawiki_db_password }}"
    #priv: "{{ mediawiki_db_name }}.*:ALL"
    priv: "*.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
  - "{{ ansible_host_list }}"